 language: node_js
 node_js:
   - "0.12"
   - "4"
   - "5"
 branches:
 only:
  - master
  - develop
 notifications:
  email:
   - nfantone@gmail.com
 script: gulp test
 before_script:
  - npm install -g gulp
