language: node_js
node_js:
- '4'
- '5'
branches:
only:
- master
- develop
notifications:
  email:
  - nfantone@gmail.com
script: gulp test && ./node_modules/.bin/codecov
before_script:
- npm install -g gulp
- npm install codecov
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: kAX/pxm24RB/pyisFCgYGaEc0vfa6HPFqu1qjxhzjBI8+I3IvKmWuyderC5EuxccZu+glCNnuxWoHXGkDf0xKHTuPk3PCs5rEQ2Cfoqyd/ZBxjkJXVWimwMJyoOsDeEw1LdOfWRRJCd98kbXa5z9m8xOaa/2doMSwj3NIVHiICRx+Y7bP5VCE8PDRpViO84R9GH1HBHQr3PjaxnPVMcQxq/c7oO9/FpEVabqSW4dQx58qhLVkPTzQ0/E58nxzcijGwg15S8DhnKOGo61zuUn/DULEj/5rjSLlwmMxbj1yqOz9Pb/EO1dbkYDkonAFO52tgvWiKnPvJJTqMVgb/Qdl571LOWWugF5SBwnkXSFgDKe5TF1Z5MWzQBkiBRm7yBjPeQN1uJXPV+F5jTjprFaR4FzDBYRXys7NwtFtpmE1pnjZ8hqX+l94Qo1Jiwr9/2XC7k1FM5RUTuY24eJogKizdUbO1cufTnWWK6LlhOFBoHZiWaaZVdRTAPpD4IiYaXE5KOrv4jqRpDNObLiCFSFV5VNDqwIv50TPLcygWmwaaT69VHAN3ilG3IvJiV+k5PBwlrYmcx3OoYL+4NutzpaWBnLXTmkdQYF0UzJUxN0CklgtJwrIn6mT5dj1KUFBIhvsbRsFxrPTu/CfCNI7o7aSzGgv5Per/dZVTdsTkdxyEU=
  on:
    tags: true
    repo: nfantone/amqp-uri
